---
# file: roles/ansible_bender/molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/${MOLECULE_DISTRO:-coglinev3/ansible}:${MOLECULE_DISTRO_VERSION:-almalinux-8}
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    cgroupns_mode: host
    privileged: true
    command: ${MOLECULE_DISTRO_CMD:-""}
provisioner:
  name: ansible
#  inventory:
#    host_vars:
#      # settings for the platform instance named 'instance'
#      instance:
#        ansible_user: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
